#!/usr/bin/env bash
DEVOPS_ROOT=$(pwd)
DEVOPS_IMAGE=hauslo-devops:latest

docker run --rm -it \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ${DEVOPS_ROOT}/:${DEVOPS_ROOT}/ \
  -w ${DEVOPS_ROOT} \
  ${DEVOPS_IMAGE} \
  "$@"
